Library/Models/Book.cs
using System.Collections.Generic;

namespace Library.Models
{
	public class Book
	{
		public int BookId { get; set; }
		public string Name { get; set; }
		public virtual ApplicationUser User { get; set; }
		public virtual ICollection<AuthorBook> Authors { get; }

		public Book()
		{
			this.Authors = new HashSet<AuthorBook>();
		}
	}
}

Library/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Library.Models;

namespace Library.Controllers
{
	[Authorize]
	public class AuthorsController : Controller
	{
		private readonly LibraryContext _db;
		private readonly UserManager<ApplicationUser> _userManager;

		public AuthorsController(UserManager<ApplicationUser> userManager, LibraryContext db)
		{
			_userManager = userManager;
			_db = db;
		}

		private Author GetAuthorFromId(int id)
		{
			return _db.Authors.FirstOrDefault(author => author.AuthorId == id);
		}

		private async Task<ApplicationUser> GetCurrentUser()
		{
			string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			return await _userManager.FindByIdAsync(userId);
		}

		public async Task<ActionResult> Index()
		{
			ApplicationUser currentUser = await GetCurrentUser();
			List<Author> userAuthors = _db.Authors.Where(entry => entry.User.Id == currentUser.Id).ToList();
			return View(userAuthors);
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Create(Author author)
		{
			author.User = await GetCurrentUser();

			_db.Authors.Add(author);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Details(int id)
		{
			Author thisAuthor = _db.Authors
				.Include(author => author.Books)
				.ThenInclude(join => join.Book)
				.FirstOrDefault(author => author.AuthorId == id);
			return View(thisAuthor);
		}

		public ActionResult Edit(int id)
		{
			Author thisAuthor = GetAuthorFromId(id);
			return View(thisAuthor);
		}

		[HttpPost]
		public ActionResult Edit(Author author)
		{
			_db.Entry(author).State = EntityState.Modified;
			_db.SaveChanges();
			return RedirectToAction("Details", new { id = author.AuthorId });
		}

		public ActionResult Delete(int id)
		{
			Author thisAuthor = GetAuthorFromId(id);
			return View(thisAuthor);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Author thisAuthor = GetAuthorFromId(id);
			_db.Authors.Remove(thisAuthor);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult AddBook(int id)
		{
			Author thisAuthor = GetAuthorFromId(id);
			ViewBag.BookId = new SelectList(_db.Books, "BookId", "Name");
			return View(thisAuthor);
		}

		[HttpPost]
		public ActionResult AddBook(Author author, int bookId)
		{
			bool duplicate = _db.AuthorBooks.Any(join => join.AuthorId == author.AuthorId && join.BookId == bookId);

			if (bookId != 0 && !duplicate)
			{
				_db.AuthorBooks.Add(new AuthorBook() { AuthorId = author.AuthorId, BookId = bookId });
			}

			_db.SaveChanges();
			return RedirectToAction("Details", new { id = author.AuthorId });
		}

		[HttpPost]
		public ActionResult DeleteBook(int joinId)
		{
			AuthorBook joinEntry = _db.AuthorBooks.FirstOrDefault(entry => entry.AuthorBookId == joinId);
			_db.AuthorBooks.Remove(joinEntry);
			_db.SaveChanges();
			return RedirectToAction("Details", new { id = joinEntry.AuthorId });
		}
	}
}

Library/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Library.Models;

namespace Library.Controllers
{
	[Authorize]
	public class BooksController : Controller
	{
		private readonly LibraryContext _db;
		private readonly UserManager<ApplicationUser> _userManager;

		public BooksController(UserManager<ApplicationUser> userManager, LibraryContext db)
		{
			_userManager = userManager;
			_db = db;
		}

		private Book GetBookFromId(int id)
		{
			return _db.Books.FirstOrDefault(book => book.BookId == id);
		}

		private async Task<ApplicationUser> GetCurrentUser()
		{
			string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			return await _userManager.FindByIdAsync(userId);
		}

		public async Task<ActionResult> Index()
		{
			ApplicationUser currentUser = await GetCurrentUser();
			List<Book> userBooks = _db.Books.Where(entry => entry.User.Id == currentUser.Id).ToList();
			return View(userBooks);
		}

		public ActionResult Create()
		{
			ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Create(Book book, int authorId)
		{
			book.User = await GetCurrentUser();
			_db.Books.Add(book);

			if (authorId != 0)
			{
				_db.AuthorBooks.Add(new AuthorBook() { AuthorId = authorId, BookId = book.BookId });
			}

			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Details(int id)
		{
			Book thisBook = GetBookFromId(id);
			return View(thisBook);
		}

		public ActionResult Edit(int id)
		{
			Book thisBook = GetBookFromId(id);
			ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
			return View(thisBook);
		}

		[HttpPost]
		public ActionResult Edit(Book book, int authorId)
		{
			bool duplicate = _db.AuthorBooks.Any(join => join.AuthorId == authorId && join.BookId == book.BookId);

			if (authorId != 0 && !duplicate)
			{
				_db.AuthorBooks.Add(new AuthorBook() { AuthorId = authorId, BookId = book.BookId });
			}

			_db.Entry(book).State = EntityState.Modified;
			_db.SaveChanges();
			return RedirectToAction("Details", new { id = book.BookId });
		}

		public ActionResult Delete(int id)
		{
			Book thisBook = GetBookFromId(id);
			return View(thisBook);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Book thisBook = GetBookFromId(id);
			_db.Books.Remove(thisBook);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult AddAuthor(int id)
		{
			Book thisBook = GetBookFromId(id);
			ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "Name");
			return View(thisBook);
		}

		[HttpPost]
		public ActionResult AddAuthor(Book book, int authorId)
		{
			bool duplicate = _db.AuthorBooks.Any(join => join.AuthorId == authorId && join.BookId == book.BookId);

			if (authorId != 0 && !duplicate)
			{
				_db.AuthorBooks.Add(new AuthorBook() { AuthorId = authorId, BookId = book.BookId });
			}

			_db.SaveChanges();
			return RedirectToAction("Details", new { id = book.BookId});
		}

		[HttpPost]
		public ActionResult DeleteAuthor(int joinId)
		{
			AuthorBook joinEntry = _db.AuthorBooks.FirstOrDefault(entry => entry.AuthorBookId == joinId);
			_db.AuthorBooks.Remove(joinEntry);
			_db.SaveChanges();
			return RedirectToAction("Details", new { id = joinEntry.AuthorId });
		}
	}
}

Library/Views/Books/AddAuthor.cshtml
@{
	Layout = "_Layout";
}

@model Library.Models.Book

<h2 id="title">Add an Author to <b>@Html.DisplayFor(model => model.Name)</b></h2>

<hr />

@using (Html.BeginForm())
{
	@Html.HiddenFor(model => model.BookId)

	@Html.Label("Select author")
	<br>
	@Html.DropDownList("AuthorId")
	<br><br>
	<input type="submit" value="save" />
}

<hr />

<p>
	@Html.ActionLink("View all books", "Index")
 |
	@Html.ActionLink("Go to homepage", "Index", "Home")
</p>

Library/Views/Books/Create.cshtml
@{
	Layout = "_Layout";
}

@model Library.Models.Book

<h2 id="title">Add a new Book</h2>

<hr />

@using (Html.BeginForm())
{
	@Html.LabelFor(model => model.Name)
	<br>
	@Html.TextBoxFor(model => model.Name)
	<br><br>
	<input type="submit" value="Add book" />
}

<hr />

<p>
	@Html.ActionLink("View all books", "Index")
 |
	@Html.ActionLink("Go to homepage", "Index", "Home")
</p>

Library/Views/Books/Delete.cshtml
@{
	Layout = "_Layout";
}

@model Library.Models.Book

<h2 id="title">Delete <b>@Html.DisplayFor(model => model.Name)</b></h2>
<h4 id="subtitle"><b>This cannot be undone!</b></h4>

<hr />

@using (Html.BeginForm())
{
	<input id="delete" type="submit" value="Delete" />
}

<hr />

<p>
	@Html.ActionLink("View all books", "Index")
 |
	@Html.ActionLink("View book", "Details", new { id = Model.BookId })
 |
	@Html.ActionLink("Go to homepage", "Index", "Home")
</p>

Library/Views/Books/Details.cshtml
@{
	Layout = "_Layout";
}

@using Library.Models;
@model Library.Models.Book

<h2 id="title">Book: <b>@Html.DisplayFor(model => model.Name)</b></h2>

<hr />

@if (Model.Authors.Count == 0)
{
	<p>This book doesn't have any authors assigned.</p>
}
else
{
	<h4><u>Authors</u></h4>
	<ul>
		@foreach (var join in Model.Authors)
		{
		 <li class="inline">
				@using (Html.BeginForm("DeleteAuthor", "Books"))
				{
					@Html.ActionLink($"{join.Author.Name}", "Details", "Authors", new { id = join.Author.AuthorId })
					@Html.Hidden("joinId", @join.AuthorBookId)
			  <input id="delete" type="submit" value="Delete" />
				}
		 </li>
		}
	</ul>
}

<hr />

<p>
	@Html.ActionLink("Add author", "AddAuthor", new { id = Model.BookId })
 |
	@Html.ActionLink("Edit", "Edit", new { id = Model.BookId })
 |
	@Html.ActionLink("Delete", "Delete", new { id = Model.BookId })
 <br>
	@Html.ActionLink("View all books", "index")
 |
	@Html.ActionLink("Go to homepage", "Index", "Home")
</p>

Library/Views/Books/Edit.cshtml
@{
	Layout = "_Layout";
}

@model Library.Models.Book

<h2 id="title">Edit <b>@Html.DisplayFor(model => model.Name)</b></h2>

<hr />

@using (Html.BeginForm())
{
	@Html.HiddenFor(model => model.BookId)

	@Html.LabelFor(model => model.Name)
	<br>
	@Html.TextBoxFor(model => model.Name)
	<br><br>
	<input type="submit" value="Save" />
}

<hr />

<p>
	@Html.ActionLink("View all books", "Index")
 |
	@Html.ActionLink("Go to homepage", "Index", "Home")
</p>

Library/Views/Books/Index.cshtml
@{
	Layout = "_Layout";
}

@using Library.Models
@model List<Library.Models.Book>

<h2 id="title">Books</h1>

 <hr />

	@if (Model.Count == 0)
	{
	 <p>No books have been added yet.</p>
	}
	else
	{
		@foreach (Book book in Model)
		{
		 <li>@Html.ActionLink($"{book.Name}", "Details", new { id = book.BookId })</li>
		}
	}

 <hr />

 <p>
		@Html.ActionLink("Add a new book", "Create")
  |
		@Html.ActionLink("Go to homepage", "Index", "Home")
 </p>